// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6437c089-1ab1-468c-a368-63b2db6ac208";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBathroomLightChange();
void onBedroomLightChange();
void onLampChange();
void onFanChange();

CloudLight bathroom_light;
CloudLight bedroom_light;
CloudLight lamp;
CloudSwitch fan;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bathroom_light, READWRITE, ON_CHANGE, onBathroomLightChange);
  ArduinoCloud.addProperty(bedroom_light, READWRITE, ON_CHANGE, onBedroomLightChange);
  ArduinoCloud.addProperty(lamp, READWRITE, ON_CHANGE, onLampChange);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
